$(document).ready(function(){
    $(".bs2editor").bs2editor({
        buttons:{
            bold:'.-bold',
            link:'.-link',
        },
        layouts:{
            linkDropDown:'.-link-dropdown',
            textarea:'.bs2editor-textarea'
        }
    });
});
